
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.2.01 EDK_Jm_SP1.2
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Exception Handling Header for MicroBlaze Processor
*
*******************************************************************/

